function [data_out, data_fs] = H_STR_SUB_READ_TDT(direc, store, t_lims, ch)

if ~exist('ch', 'var')
    
    t = TDTbin2mat(direc, 'T1', t_lims(1)/1000, ...
        'T2', t_lims(2)/1000, ...
        'TYPE',{'streams'}, ...
        'STORE', store);
    
else
    
    t = TDTbin2mat(direc, 'T1', t_lims(1)/1000, ...
        'T2', t_lims(2)/1000, ...
        'TYPE',{'streams'}, ...
        'STORE', store, ...
        'CHANNEL', ch);
end
                
data_fs = eval(['t.streams.' store '.fs']);
data_out = eval(['t.streams.' store '.data']);

end