function P_PERFBAR_VS(f, ax, data, info)

fprintf('\n Begin: Plotting Performance Bars. \n')

hold off;
set(0, 'currentfigure', f);
set(f, 'currentaxes', ax);
hold on;

ctr = 1;

bar(ctr,[sum(data.trial_by.correct & data.trial_by.catch == false) / sum(data.trial_by.catch == false)], ...
        'facecolor', 'w', 'linewidth', 2)
    
ctr = ctr+1;
    
bar(ctr,[sum(data.trial_by.correct & data.trial_by.catch == true) / sum(data.trial_by.catch == true)], ...
        'facecolor', 'w', 'linewidth', 2)

ctr = ctr + 2;
    
for pitt = 1 : numel(data.trial_stat.uniq_targ_col)
    
    col = G_COL(data.trial_stat.uniq_targ_col(pitt));
    
    bar(ctr,sum(data.trial_by.correct(data.trial_by.targ_col == ...
        data.trial_stat.uniq_targ_col(pitt) & ...
        data.trial_by.catch == false)) / ...
        numel(data.trial_by.correct(data.trial_by.targ_col == ...
        data.trial_stat.uniq_targ_col(pitt) & ...
        data.trial_by.catch == false)),...
        'facecolor', col, 'linewidth', 2)
    ctr=ctr+1;
end

ctr = ctr+1;

for pitt = 1 : numel(data.trial_stat.uniq_dist_col)
    
    col = G_COL(data.trial_stat.uniq_dist_col(pitt));
    bar(ctr,sum(data.trial_by.correct(data.trial_by.dist_col == ...
        data.trial_stat.uniq_dist_col(pitt) & ...
        data.trial_by.catch == false)) / ...
        numel(data.trial_by.correct(data.trial_by.dist_col == ...
        data.trial_stat.uniq_dist_col(pitt) & ...
        data.trial_by.catch == false)), ...
        'facecolor', col, 'linewidth', 2)
    ctr=ctr+1;
end

ctr = ctr + 1;

for pitt = 1 : numel(data.trial_stat.uniq_catch_col)
    
    col = G_COL(data.trial_stat.uniq_catch_col(pitt));
    bar(ctr,sum(data.trial_by.correct(data.trial_by.targ_col == ...
        data.trial_stat.uniq_catch_col(pitt) & ...
        data.trial_by.dist_col == ...
        data.trial_stat.uniq_catch_col(pitt))) / ...
        numel(data.trial_by.correct(data.trial_by.targ_col == ...
        data.trial_stat.uniq_catch_col(pitt) & ...
        data.trial_by.dist_col == ...
        data.trial_stat.uniq_catch_col(pitt))), ...
        'facecolor', col, 'linewidth', 2)
    ctr=ctr+1;
end
    
set(gca, 'linewidth', 2, 'ylim', [0 1], 'fontsize', 12, ...
    'xtick', [1, 2, (3 + numel(data.trial_stat.uniq_targ_col)/2 + .5), ...
    ((3 + numel(data.trial_stat.uniq_targ_col)+1) + numel(data.trial_stat.uniq_targ_col)/2 + .5), ...
    ((4 + 2*numel(data.trial_stat.uniq_targ_col)+1) + numel(data.trial_stat.uniq_targ_col)/2 + .5)], ...
    'xticklabel', {'O: Go', 'O: Catch', 'SC: Go', 'DC: Go', 'C: Catch'})

xtickangle(45)

axis square
box off
title('Success Rate by Condition');
ylabel('Success Rate');
xlabel('Condition');

end